[project]
name = "project"
version = "0.1.0"
description = "MLOps starter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "datasets>=4.8.4",
    "dvc-gdrive>=3.0.1",
    "dvc-s3>=3.3.0",
    "dvc[gdrive]>=3.67.1",
    "evaluate>=0.4.6",
    "fastapi>=0.136.1",
    "langchain-core>=1.4.0",
    "langchain-openai>=1.2.2",
    "numpy>=2.4.4",
    "pandas>=3.0.1",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.8.0",
    "torch==2.11.0+cu128",
    "transformers>=5.5.4",
    "uvicorn[standard]>=0.46.0",
]

[project.scripts]
project = "lyubava.cli:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]
