apiVersion: v1
kind: Secret
metadata:
  name: lyubava-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: mlflow123
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  OPENROUTER_API_KEY: ""
