apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../minikube

configMapGenerator:
  - name: lyubava-config
    literals:
      - POSTGRES_DB=mlflow
      - POSTGRES_USER=mlflow
      - MLFLOW_S3_BUCKET=lyubava-mlflow-artifacts
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_DEFAULT_REGION=us-east-1
secretGenerator:
  - name: lyubava-secrets
    behavior: replace
    envs:
      - secrets.argocd.env

images:
  - name: lyubava-api
    newName: ghcr.io/tarasovegor/lyubava-emotion-aware-ai-companion
    newTag: api-latest
  - name: lyubava-frontend
    newName: ghcr.io/tarasovegor/lyubava-emotion-aware-ai-companion
    newTag: frontend-latest
  - name: lyubava-mlflow
    newName: ghcr.io/tarasovegor/lyubava-emotion-aware-ai-companion
    newTag: mlflow-latest

patches:
  - path: patches/ghcr-image-pull.yaml
  - path: patches/api-openrouter-secret.yaml
